# Generated by Django 5.1.7 on 2025-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_xmlfeedlink_updated_at'),
        ('core', '0006_contact_properties_contact_remarks_contact_selec_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='accounts.propertydata'),
        ),
    ]
