# Generated by Django 5.1.7 on 2025-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_oauthtoken_company_name_alter_oauthtoken_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
