# Generated by Django 5.1.7 on 2025-05-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_oauthtoken_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'verbose_name': 'OAuth Token', 'verbose_name_plural': 'OAuth Tokens'},
        ),
    ]
