# Generated by Django 5.1.7 on 2025-09-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_oauthtoken_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_added']},
        ),
    ]
