# Generated by Django 5.1.7 on 2025-04-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_xmlfeedlink_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='xml_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xmlfeedlink', to='accounts.xmlfeedlink'),
        ),
    ]
