# Generated by Django 5.1.7 on 2025-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_propertydata_xml_url'),
        ('core', '0011_alter_oauthtoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfeedlink',
            name='subaccounts',
            field=models.ManyToManyField(related_name='xml_feeds', to='core.oauthtoken'),
        ),
    ]
