# Generated by Django 5.1.7 on 2025-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_xmlfeedlink_subaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfeedlink',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
